### ISSUE TITLE
SQL syntax error at or near "where" Position: 458 when running AchillesHeel

### ISSUE THREAD

**Issue by SulevR** [OHDSI/Achilles#266] opened 2018-04-24 09:12 UTC
Using the OMOP CDM 5.3 and Achilles from github. Running into SQL error:

### Expected behavior

No error.

### Actual behavior

```
Running Achilles:
Executing Achilles Heel. This could take a while
  |============================================                          |  62%Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "where"
  Position: 458

```
### Steps to reproduce behavior

```
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "where"
  Position: 458

SQL:
insert into ohdsi.ACHILLES_results_derived (statistic_value,stratum_1,measure_id)    
select
  CAST(100.0*st.val/statistic_value AS NUMERIC) as statistic_value,
  CAST('Condition' AS VARCHAR(255)) as stratum_1, CAST(  'UnmappedData:byDomain:Percentage' AS VARCHAR(255)) as measure_id
from ohdsi.achilles_results_derived
join (select statistic_value as val from ohdsi.achilles_results_derived where measure_id like 'UnmappedData:ach_401:GlobalRowCnt') as st
where measure_id ='ach_401:GlobalRowCnt'

R version:
R version 3.4.3 (2017-11-30)

Platform:
x86_64-apple-darwin15.6.0

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.5)
- rjson (0.2.15)
- DatabaseConnector (2.1.0)
- SqlRender (1.4.10)
- devtools (1.13.5)

```

**Comment by t-abdul-basser** [comment] 2018-04-24 17:35
Yes, this is a duplicate of #260. Thank you for reporting.

**Closed by t-abdul-basser** 2018-04-24 17:35 UTC
