### ISSUE TITLE
Achilles 1.6.1 - ERROR: syntax error at or near "." Position: 22

### ISSUE THREAD

**Issue by lchonghua** [OHDSI/Achilles#323] opened 2018-10-04 20:12 UTC
### Expected behavior
No error should be raised.

### Actual behavior
Error: 
org.postgresql.util.PSQLException: ERROR: syntax error at or near "." Position: 22

3 tables were created in result schema:
- achilles_analysis
- achilles_results
- achilles_results_dist

**** an additional table named "s_tmpach_1823" is also created in my cdm schema.**
### Steps to reproduce behavior
Run the following command:
```
library(Achilles)
connectionDetails <- createConnectionDetails(dbms="postgresql", 
                                             server="localhost/OHDSI",
                                             user="ohdsi_admin_user",
                                             password="admin1",
                                             schema="cdm_synpuf_1k",
                                             port="5432")
achilles(connectionDetails, 
         cdmDatabaseSchema = "cdm_synpuf_1k", 
         resultsDatabaseSchema="result_cdm_synpuf",
         vocabDatabaseSchema = "cdm_synpuf_1k",
	 numThreads = 1,
         sourceName = "SYNPUF_1K", 
         cdmVersion = "5.2.2",
         runHeel = TRUE,
         runCostAnalysis = FALSE)
```
Error report details:
DBMS: 
postgresql

Error: 
org.postgresql.util.PSQLException: ERROR: syntax error at or near "." Position: 22

SQL:
DROP TABLE IF EXISTS .tmpach_ch_condition

R version:
R version 3.5.0 (2018-04-23)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.6.1)
- OhdsiRTools (1.5.5)
- httr (1.3.1)
- openxlsx (4.1.0)
- rjson (0.2.20)
- DatabaseConnector (2.2.0)
- SqlRender (1.5.2)
- devtools (1.13.6)

**Comment by alondhe** [comment] 2018-10-04 20:33
What happens when you run the dropAllScratchTables function?

**Comment by lchonghua** [comment] 2018-10-06 04:51
I ran this function:
dropAllScratchTables(connectionDetails, "cdm_synpuf_1k",
  tempAchillesPrefix = "tmpach", tempHeelPrefix = "tmpheel",
  numThreads = 1, tableTypes = c("achilles", "heel",
  "concept_hierarchy")),
and it executed a bunch of sqls without raising any errors. But when I checked cdm_synpuf_1k schema, the s_tmpach_1832 table still exists.

**Comment by chrisknoll** [comment] 2018-10-06 13:17
looks like there's a missing schema?

```
DROP TABLE IF EXISTS .tmpach_ch_condition
```
Where's the schema before ```.tmpach_ch_condition```?

**Comment by lchonghua** [comment] 2018-10-07 03:00
> looks like there's a missing schema?
> 
> ```
> DROP TABLE IF EXISTS .tmpach_ch_condition
> ```
> Where's the schema before `.tmpach_ch_condition`?

Sorry, I am not sure where does this come from. All I did was running the achilles command stated above in order to create tables for Altas. But as far as I understand, the schema should be appended automatically by the Achilles command, is it correct?

**Comment by chrisknoll** [comment] 2018-10-07 03:09
well, if for some reason the paramater was passed in as an empty string, then it'll replace the token with empty (in that case it's user error) or there's a legit bug in that they did not specify a schema replace-token in front of that particular drop table statement.

**Comment by alondhe** [comment] 2018-10-07 22:37
Hi @lchonghua -- I'm unable to reproduce this. Do you mind clearing your session's environment variables, terminating the R session, and re-running?

**Comment by lchonghua** [comment] 2018-10-08 22:06
> Hi @lchonghua -- I'm unable to reproduce this. Do you mind clearing your session's environment variables, terminating the R session, and re-running?

Okay, here is what I did:

First of all, here is my database setting:
- database name: OHDSI
	- schema 1: cdm (holds the synpuf 1k dataset and vocabulary)
	- schema 2: result
	- schema 3: webapi (from WebAPI 2.5.0)

1. Restarted my vm.
2. manually drop the temp table left from failure last operation using the following command:
	drop table cdm.s_tmpach_1823;

3. create a new result schema ("result") in the same database as cdm schema for testing purpose

4. run the ddl generated by http://myIPAddress:8080/WebAPI/ddl/results?dialect=postgresql&schema=result
	This create 22 tables in the result schema.
	note: a lot of schema name is not correctly formed
	example: 
		@results_database_schema.concept_hierarchy
		@vocab_database_schema.concept
       I ended up manually replacing them with "result.tableName" and "cdm.tableName".
 
5. open R session in the terminal and run the following commands:
	library(Achilles)
	connectionDetails <- createConnectionDetails(dbms="postgresql", 
                                             server="localhost/OHDSI",
                                             user="ohdsi_admin_user",
                                             password="admin1",
                                             schema="cdm",
                                             port="5432")
	
	achilles(connectionDetails, 
         cdmDatabaseSchema = "cdm", 
         resultsDatabaseSchema="result",
         vocabDatabaseSchema = "cdm",
	 numThreads = 1,
         sourceName = "SYNPUF_1K", 
         cdmVersion = "5.2.2",
         runHeel = TRUE,
         runCostAnalysis = FALSE)

I got the same result as described above.

**Comment by alondhe** [comment] 2018-10-23 13:50
Hi @lchonghua -- we've released a few bugfixes that I believe should resolve this issue. Can you re-install Achilles and re-run?

**Comment by alondhe** [comment] 2018-11-02 18:37
Closing for now. @lchonghua please let me know if you continue to face this issue.

**Closed by alondhe** 2018-11-02 18:37 UTC
