### ISSUE TITLE
Execution on Oracle 11g fails

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#290] opened 2018-07-31 07:17 UTC
### Expected behavior
It's expected that Achilles Heel step is executed correctly

### Actual behavior
Actually execution fails due to SQL error. See log below:

Executing Achilles Heel. This could take a while
  |======                                                                |   8%
Error: Error executing SQL:
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

DBMS:
oracle

Error:
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

SQL:
insert into results.ACHILLES_results_derived (statistic_value,measure_id)    
SELECT CAST(100.0*count_value/statistic.total_pts AS FLOAT) as statistic_value,
   CAST(CONCAT('ach_', CONCAT(CAST(analysis_id as VARCHAR(10)), ':Percentage')) AS VARCHAR(100)) as measure_id
  FROM results.achilles_results 
	cross join (SELECT count_value as total_pts FROM results.achilles_results r   WHERE analysis_id =1 ) as statistic
    WHERE analysis_id in (2000,2001,2002,2003) 

R version:
R version 3.5.0 (2018-04-23)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.5)
- rjson (0.2.20)
- SqlRender (1.5.1)
- DatabaseConnector (2.1.3)

### Steps to reproduce behavior
Execute ACHILLES from R for OMOP CDM dataset. The problem happens with CDM 5.0.1 version if it does make sense.

**Comment by t-abdul-basser** [comment] 2018-07-31 12:50
Thank you for documenting this. Duplicate of #287.

Workaround: Use latest release rather than master branch.

**Closed** 2018-10-23 14:08 UTC
Labels: bug
