### ISSUE TITLE
ExportToJson issues for CDMv5 and Postgres

### ISSUE THREAD

**Issue by bandazagorath** [OHDSI/Achilles#82] opened 2016-01-12 19:04 UTC
Code crashes when running exportToJson:

Error:
org.postgresql.util.PSQLException: ERROR: relation "achilles_results" does not exist
  Position: 580

Due to the fact that the export SQL code is not fully SQLRender friendly. For example:
<code>
select * from ACHILLES_results where analysis_id = 400  
</code>
From: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/export_v5/condition/sqlConditionTreemap.sql line 5 - and all other instances of queries to achilles_results.

The "achilles_results" table should have the prefix: <code>@resultsDatabaseSchema</code> or <code> @cdm_database_schema </code> - which in our case, this was the schema that all the Achilles and Achilles Heel results were written by the package.

**Comment by jmbanda** [comment] 2016-01-12 19:06
My apologies, reported this issue with the wrong Github account!

**Comment by chrisknoll** [comment] 2016-01-12 19:30
Good catch, do you think you could make a PR to update the scripts? sounds like anything that has from ACHILLES_results should have from @resultsDatabaseSchema (could do a bulk find-and-replace in files for this).  Otherwise I can take this on but it will be a few days before I can commit a change.

note on when to use @results_database_schema (note it is not @resultsDatabaseSchema) vs. @cdm_database_schema:  When refering to a table in the cdm, you use @cdm_database_schema.  Example: Concept, Person, Drug_exposure, etc.  The @results_database_schema is the prefix on tables created in the Achilles analyssis (achilles_results, achilles_results_dist, etc).

In your example the prefix there should be @results_database_schema.

Let me know if you want to take this on or if I should.

-Chris

**Comment by jmbanda** [comment] 2016-01-12 19:41
@chrisknoll Sure, I can do a pull request and make the fix. Upon further inspection, there is also a bug on Achilles.R (https://github.com/OHDSI/Achilles/blob/master/R/Achilles.R#L69) and this is why the results were written to our <code>@cdm_database_schema</code>:

<code>
......
resultsDatabaseSchema = cdmDatabaseSchema, 
.....
<code>

This should be:
<code>
....
resultsDatabaseSchema = resultsDatabaseSchema,
.....
</code>

I'll add that extra fix as well.

**Comment by chrisknoll** [comment] 2016-01-12 19:55
That last thing you found is not a bug!! It means that if you don't supply a resultsDatabaseSchema parameter to achilles, it will default to use the cdmDatabaseSchema. So don't make that change :)  In your case you'd have to pass the 2 parameters cdmDatabaBaseSchema and resultsDatabaseSchema in the call to achilles().

In our internal environment we do a achilles(myConDetails, cdmDatabaseSchema="myCdmSchema", resultsDatabaseSchema="myResultSchema") when we want to put the achilles results into a separate schema. Other times, the cdm schema _is_ the results schema, so we just call it like achilles(myConDetails, cdmDatabaseSchema="myCdmSchema")  The resultsDatabaseSchema will be assigned tot he same value as the cdmDatabaseSchema parameter, but the sqlRender still needs to replace all the @results_database_schema tokens with something, so in this second case, it will replace it with the value of the cdmDatabaseSchema parameter.

-Chris

**Comment by jmbanda** [comment] 2016-01-12 20:01
Ok, however, when following the documentation:

<code>
connectionDetails <- createConnectionDetails(dbms="postgresql", server="localhost/BLAH", user="BLAH", password="BLAH", schema="ohdsiv5_stride6", port="5432")
AchillesResults <- achilles(connectionDetails, "ohdsiv5_stride6", "results_stride6", cdmVersion = "5")
exportToJson(connectionDetails, "ohdsiv5_stride6", "results_stride6", "/labs/shahlab/users/jmbanda/achilles", cdmVersion = "5")
</code>

The results are NOT written into "results_stride6", but in "ohdsiv5_stride6" so there is an issue somewhere. Either the documentation or the code :)

I will just make the other fixes we discussed, and leave this one alone.

**Comment by chrisknoll** [comment] 2016-01-12 20:29
Ok, That's interesting, I wonder if the order of the parameters is somehow being confused, but if you call it like this:
achilles(connectionDetails, cdmDatabaseSchema = "ohdsiv5_stride6", resultsDatabaseSchema = "results_stride6", cdmVersion = "5")

It should write the results into the correct schema.  If not, let me dig into it.  Mabye one of the INSERT statements is missing a @results_database_schema token and it's messing it up that way?

**Comment by chrisknoll** [comment] 2016-01-12 20:42
@jmbanda , I got it.  Here's the declaration of the function:

~~~ r
achilles <- function (connectionDetails, 
                      cdmDatabaseSchema, 
                      oracleTempSchema = cdmDatabaseSchema,
                      resultsDatabaseSchema = cdmDatabaseSchema, 
                      sourceName = "", 
                      analysisIds, 
                      createTable = TRUE, 
                      smallcellcount = 5, 
                      cdmVersion = "4", 
                      runHeel = TRUE,
                      validateSchema = FALSE){
~~~~

So, without naming the parameters, calling 
~~~ r
AchillesResults <- achilles(connectionDetails, "ohdsiv5_stride6", "results_stride6", cdmVersion = "5")
~~~~

Assigns connectionDetails to the connectioDeails parameter, "ohdsiv5_stride6" to cdmDatabaseSchema, "results_stride6" to oracleTempSchema, and since resultsDatabaseSchema wasn't defined (the final parameter was associated to cdmVersion), it used the cdmDatabaseSchema by default.

Basically, when the 'oracleTempSchema' parameter was introduced, it broke anyone who was used to doing the call the way you call it.  So, the answer here is to explicitly name the parameters when you call the achilles() function, OR we change the order like so:

~~~ r
achilles <- function (connectionDetails, 
                      cdmDatabaseSchema, 
                      resultsDatabaseSchema = cdmDatabaseSchema, 
                      sourceName = "", 
                      analysisIds, 
                      oracleTempSchema = cdmDatabaseSchema,
                      createTable = TRUE, 
                      smallcellcount = 5, 
                      cdmVersion = "4", 
                      runHeel = TRUE,
                      validateSchema = FALSE){

~~~~

But, honestly, there's so many parameters, it would probably be a 'best practice' that when calling these methods, you explicitly name the parameters in the call.

-Chris

**Comment by chrisknoll** [comment] 2016-01-12 20:54
Ok, updated the docs, thanks for pointing that out too!  Let me know if there's anything you need.

**Comment by jmbanda** [comment] 2016-01-12 21:14
Thanks! I will do a PR with my latest changes later today!

**Comment by jmbanda** [comment] 2016-01-13 00:05
@chrisknoll I have updated my branch with what worked for me, but it is sort of a hack as it ONLY works when you saved the results (by accident or on purpose to the cdmDatabaseSchema location). 

The bigger issue comes in exportToJson.R and ALL the generate**** functions since they do not pass the parameter resultsDatabaseSchema and it needs to be passed to them in order for the originally discussed changes to work. I will add all of those changes in my next commit to my branch (so don't merge it just yet), but for now I just added what I needed to get it to work with what I have.

**Comment by chrisknoll** [comment] 2016-01-13 00:17
Oy!  Ok, very very good catch. No wonder we weren't seeing errors doing the work on our side, we store the results in the same schema!  Ok, so that additional fix will be very useful, thank you.

**Comment by schuemie** [comment] 2016-01-13 08:10
I've always used Achilles by storing the results in a different schema, and it has worked fine for me. The reason is [this line](https://github.com/OHDSI/Achilles/blob/master/R/exportToJson.R#L98), where the results schema is specified in the connection details. Upon connecting to the database, the active schema will be set to what was specified in the connection details.

**Comment by jmbanda** [comment] 2016-01-13 08:45
@schuemie Indeed that line should work, but on our Postgres server it completely ignores which schema is being set and relies on the explicit SQL render translated ones. Do you have any particular setting in Postgres that would enable this to work?

**Comment by schuemie** [comment] 2016-01-13 09:41
@jmbanda I'm not sure why it is not working on your server. As you can see [here](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L282), a ```SET SEARCH_PATH TO``` command should be sent after the connection is established. 

Could you try the following code to see if it works?
```r
library(DatabaseConnector)
connectionDetails <- createConnectionDetails(dbms="postgresql", server="localhost/BLAH", user="BLAH", password="BLAH", schema="ohdsiv5_stride6", port="5432")
conn <- connect(connectionDetails)
querySql(conn, "SELECT COUNT(*) FROM person")
```

**Comment by jmbanda** [comment] 2016-01-13 18:21
It does work:
<code>
    COUNT
1 1867399
</code>
So the problem might be somewhere else that is not setting the schema correctly or changing it to something else in Achilles. Should I do the explicit changes to be sure? or investigate further? What would be best practices in this case? put the explicit schema on all SQL statements or find why the schema is not being set properly.

**Comment by chrisknoll** [comment] 2016-01-13 19:16
My vote is we do not resort to search paths, and explicitly qualify all tables using the @cdm_database_schema and @results_database_schema placeholders in the scripts.

Also, I understand that for your purposes you made all the achilles_results tables qualified with @cdm_database_schema in your branch commits, but the final commit should have all achilles_results tables qualfied with @results_database_schema, and cdm tables resolved with @cdm_database_schema. It might be worthwhile to run your entire process using the proper parameter calls and @cdm_database_schema/@results_database_schema in the final build of Achilles.

Sorry that this isn't as straight-forward as I would have hoped!  If this is exceeding the amount of time you wanted to spend on this, let me know, I have availability starting tomorrow to pitch in and also you doing most of the legwork here exposes where the changes need to be made.

-Chris

**Comment by jmbanda** [comment] 2016-01-13 20:43
@chrisknoll I can tackle it, not problem -  got some time to kill as I re-run the current master release of Achilles with the explicit variable assignments in the calls, which will take 10+ hours. I have just updated with a new commit changing my nasty @cdm_database_schema hack into the proper @results_database_schema. And will add the parameter to the function calls and test it before my next commit. Will let you know when it is ready.

**Comment by chrisknoll** [comment] 2016-01-13 22:06
You're the best!  Thank you.

**Comment by jmbanda** [comment] 2016-01-14 21:50
@chrisknoll ok, I did a push with all the parameters passed properly to the generate*** functions (and all their calls to sqlrender). I also added the same SQL fix to the V4 code export code. I have tested and exported with no issues on v5. However, a new issue surfaced that left me with a mostly empty achilles export (but no errors) results. When doing the Achilles heel check it fails to detect all my gender, race, ethnicity concepts and marks them as:

<code>
ERROR: 2-Number of persons by gender; 3 concepts in data are not in vocabulary
ERROR: 4-Number of persons by race; 6 concepts in data are not in vocabulary 
ERROR: 5-Number of persons by ethnicity; 3 concepts in data are not in vocabulary
</code>

I am quadruple sure that they are properly mapped, restricted to the appropriate domain_id (for the most part), I have some that are indeed mapped to 0 (per Patrick's recommendation when I don't have a match), which is indeed not the right vocabulary domain. Here is what I have for analysis_id = 2 in the achilles_results table:

analysis_id | stratum_1 | stratum_2 | stratum_3 | stratum_4 | stratum_5 | count_value |
---| --- | --- | --- | --- | --- | --- |
2 | 0 | | | | | 0  |
2 |  8507 | | | | | 856056 |
2 |  8532 | | | | | 1009684 |

This should not return the ERROR: 2  for all three concepts right - only for one of them? or am I missing something? I am using vocabulary v5.0 17-JUL-15

**Comment by chrisknoll** [comment] 2016-01-14 23:13
Here's the Heel query that does that test:

~~~ sql
SELECT or1.analysis_id,
	'ERROR: ' + cast(or1.analysis_id as VARCHAR) + '-' + oa1.analysis_name + '; ' + cast(COUNT_BIG(DISTINCT stratum_1) AS VARCHAR) + ' concepts in data are not in vocabulary' AS ACHILLES_HEEL_warning,
  4 as rule_id,
  COUNT_BIG(DISTINCT stratum_1) as record_count
FROM @results_database_schema.ACHILLES_results or1
INNER JOIN @results_database_schema.ACHILLES_analysis oa1
	ON or1.analysis_id = oa1.analysis_id
LEFT JOIN @cdm_database_schema.concept c1
	ON or1.stratum_1 = CAST(c1.concept_id AS VARCHAR)
WHERE or1.analysis_id IN (
		2,
		4,
		5,
		200,
		301,
		400,
		500,
		505,
		600,
		700,
		800,
		900,
		1000,
		1609,
		1610
		)
	AND or1.stratum_1 IS NOT NULL
	AND c1.concept_id IS NULL
GROUP BY or1.analysis_id,
	oa1.analysis_name;
~~~

Would you mind running this query directly on your data?  Note you'll have to do a find/replace on the @cdm_database_schema and @results_database_schema. To make the output simpler, you can change the IN clause to just put analysis_id 2 in there.

This query essentially takes the values from STRATUM_1 from those analysis_ids (it assumes that stratum_1 are concepts) and left joins over to vocabulary.  If the left join results in a null, the the concept_id wasn't in there.  So the output of the query finds invalid conceptIDs.  

So, let's run the above query, see if you get any rows, and if you do get rows, let's pull it apart to see why we're not successfully joining from your STRATUM_1 column.

-Chris

**Comment by jmbanda** [comment] 2016-01-15 02:13
Ok, figured out my problem. I had a total brain fart moment as I did not load the concept table on the Postgres server....... Leaving everything to run overnight.

**Comment by chrisknoll** [comment] 2016-01-21 17:06
Hi, just circling back, how are you coming along with this?  Anything I can help with?

**Comment by jmbanda** [comment] 2016-01-21 17:17
@chrisknoll Hello, all is good now! I have ran Achilles multiple times for CDMv5 and Postgres using my forked branch with the changes and it all runs fine!. I am testing how Achilles changes when I add stuff in different places. However, I have a question: Why is are the condition_occurrence reports tied only to concept_id's found in SNOMED and Medra? From what I understand and how I usually populate the table, I get all conditions from our ICD9s. So if I just load them using the ICD9 concepts in the vocabulary, my Achilles reports are empty. IF I try to map the ICD9 to SNOMED I end up dropping about 75% of my codes. How are you guys doing this mapping? Thanks!

**Comment by chrisknoll** [comment] 2016-01-22 03:47
Hi,  Short story: only standard concepts go into condition_occurrence.  Long story, let's make a forum post at forums.ohdsi.org about mapping ICD9s.  I'm pretty sure, however, that the latest V5 vocabulary has mappings for most (if not all) ICD9s to SNOMED.  

For this issue, can I merge in your pull request and close this issue?

**Comment by chrisknoll** [comment] 2016-01-26 16:00
Ok, PR has been merged. Please pull latest master for the updates.

**Closed by chrisknoll** 2016-01-26 16:00 UTC
