### ISSUE TITLE
Issue with devtools install_github (Error in read.dcf(path) :    Found continuation line starting ')

### ISSUE THREAD

**Issue by mfelz** [OHDSI/Achilles#349] opened 2018-11-20 19:10 UTC
I'm having issues installing Achilles in my environment with devtools, here's what I did to get the error:
- Installed Devtools (v2.0.1) in R environment (windows 32 bit v3.5.1)
- Ran command `devtools::install_github("OHDSI/Achilles")`
- Received the following error:
`Error in read.dcf(path) : 
  Found continuation line starting '    person("Patrick" ...' at begin of record.`

It looks like the error is in line 7 of ["DESCRIPTION" file](https://github.com/OHDSI/Achilles/blob/master/DESCRIPTION) in the OHDSI/Achilles repo.

Seems similar to [devtools issue 1900](https://github.com/r-lib/devtools/issues/1900)

**Comment by alondhe** [comment] 2018-11-21 17:06
Hmm, not able to reproduce this. @schuemie have you ever seen anything like this? I tried using the "Authors@R" / person array convention you have in the CohortMethod DESCRIPTION file, perhaps I don't have it well formed.

**Comment by schuemie** [comment] 2018-11-23 10:53
I'm able to reproduce this problem when I update to the latest version of devtools. 

The DESCRIPTION file looks fine to me. The [DESCRIPTION file in another package](https://github.com/OHDSI/SelfControlledCohort/blob/master/DESCRIPTION) looks very similar, and that package can be installed without issue.

I also find it odd that I can build Achilles just fine in RStudio.

**Comment by schuemie** [comment] 2018-11-23 12:20
After replacing all spaces in the DESCRIPTION file with single tabs I can now install using devtools. 

@mfelz : could you try installing again?

**Comment by mfelz** [comment] 2018-11-23 18:19
@schuemie the devtools install works now. 

I think it was an issue with the most recent version of devtools, specifically the "install_github" function. Downloading a zip of the repo and using the devtools "install_local" function was the way I got around the issue in the first place.

**Comment by schuemie** [comment] 2018-11-25 06:01
Thanks!

**Comment by alondhe** [comment] 2018-11-27 15:54
Hmm, just encountered this error now on a brand new install of devtools and Achilles.

**Comment by don-torok** [comment] 2018-12-31 21:31
Using RStudio I'm getting the following error.
install_github("ohdsi/SqlRender")
Error in read.dcf(path) : 
  Found continuation line starting '    person("Martijn" ...' at begin of record.

**Comment by t-abdul-basser** [comment] 2019-01-02 22:18
Thanks @don-torok. What version of devtools are you using?

**Comment by don-torok** [comment] 2019-01-02 23:18
2.0.1

**Comment by t-abdul-basser** [comment] 2019-01-03 22:38
I am unable to re-produce using devtools v2.0.1.

**Comment by t-abdul-basser** [comment] 2019-01-07 19:23
Thanks @schuemie !

**Comment by t-abdul-basser** [comment] 2019-01-14 18:20
Thanks for looking further into this. Based on the release cadence for devtools, we can expect that this fix might make it into CRAN soon, no?

**Comment by schuemie** [comment] 2019-01-15 05:09
I really have no idea. They tend to work in 'sprints', so lots of concentrated effort for a short time, then nothing for a very long time. I think they just closed a sprint, so could be next week, next month, or next year that they get around to it.

**Comment by anonymous34** [comment] 2019-02-13 22:12
@schuemie I am going through the steps here to install achilles:

[https://github.com/OHDSI/Achilles](url)

I tried with install_local from devtools and remotes, but I am getting the same error for both saying it cannot find package OHDSITools:  For remotes, it looks like this:

> remotes::install_github("OHDSI/Achilles")
Downloading GitHub repo OHDSI/Achilles@master
Skipping 1 packages not available: OhdsiRTools
Installing 28 packages: BH, bindr, bindrcpp, bit, DatabaseConnector, DatabaseConnectorJars, DBI, dplyr, fansi, fastmatch, ff, ffbase, OhdsiRTools, ParallelLogger, pillar, pkgconfig, plogr, purrr, rJava, rjson, snow, SqlRender, tibble, tidyselect, triebeard, urltools, utf8, XML
Error: (converted from warning) package ‘OhdsiRTools’ is not available (for R version 3.5.2)
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Any ideas?  Thank you

**Comment by schuemie** [comment] 2019-02-14 15:29
Yes, sorry, that may be my fault. I removed OhdsiRTools from the remotes section in the DESCRIPTION file. 

For now you can work around it by first running:
```r
devtools::install_github("OHDSI/OhdsiRTools")
```

Could someone please remove all dependencies on OhdsiRTools in ACHILLES? All relevant functions have been moved to ParallelLogger, which is available in CRAN.

**Comment by alondhe** [comment] 2019-02-14 16:03
Hi @schuemie , sorry for the delay on that. Making a PR today.

**Comment by alondhe** [comment] 2019-02-19 22:52
@anonymous34 can you try the latest version of Achilles (we merged some fixes in the last few days)

**Comment by alondhe** [comment] 2019-03-07 01:03
Closing as I believe we have fixed the issue on our side

**Closed by alondhe** 2019-03-07 01:03 UTC
