### ISSUE TITLE
Achilles DatabaseConnector Error on exit

### ISSUE THREAD

**Issue by sudoshi** [OHDSI/Achilles#746] opened 2023-12-04 20:01 UTC
This is the script I ran:

```

> #load Libraries
> 
> library(SqlRender)
> library(DatabaseConnector)
> library(Achilles)
> 
> #Db Connection
> 
> path_to_driver <- "/home/acumenus/Projects/drivers"
> 
> connectionDetails <- createConnectionDetails(
>   dbms = "postgresql",
>   server = "localhost/omop",
>   port = "5440",
>   user = "postgres",
>   password = "acumenus",
>   pathToDriver = path_to_driver
> )
> 
> #Generate OHDSI Achilles analysis
> results <- achilles(
>   connectionDetails,
>   cdmDatabaseSchema = "synthea100k_cdm",
>   resultsDatabaseSchema = "synthea100k_results",
>   vocabDatabaseSchema = "synthea100k_cdm",
>   sourceName = "omop",
>   createTable = TRUE,
>   smallCellCount = 5,
>   cdmVersion = "5.4",
>   createIndices = TRUE,
>   numThreads = 1,
>   tempAchillesPrefix = "tmpach",
>   dropScratchTables = TRUE,
>   sqlOnly = FALSE,
>   outputFolder = "output",
>   verboseMode = TRUE,
>   optimizeAtlasCache = TRUE,
>   defaultAnalysesOnly = TRUE,
>   updateGivenAnalysesOnly = FALSE,
>   excludeAnalysisIds = FALSE,
>   sqlDialect = "postgresql"
> )

```

This was the exit output:

```
Executing SQL took 0.00348 secs
Temporary Achilles tables removed from schema #
Temporary Achilles tables removed from schema #
Connecting using PostgreSQL driver
  |============================================================================================================| 100%
Executing SQL took 1.04 secs
Connecting using PostgreSQL driver
Optimizing atlas cache
Optimizing atlas cache
Optimizing atlas cache
  |============================================================================================================| 100%
Executing SQL took 5.43 mins
Atlas cache was optimized
Atlas cache was optimized
Atlas cache was optimized
[Total Runtime] 42.360455 mins
[Total Runtime] 42.360455 mins
An error occurred while the 'DatabaseConnector' package was updating the RStudio Connections pane:
Error in NULL: host must be a single element of type 'character'
If necessary, these warnings can be squelched by setting `options(rstudio.connectionObserver.errorsSuppressed = TRUE)`.
```

However, all the Achilles tables seem to have been written correctly there were no errors in any individual analysis.  This is the first time I have seen such an error with an Achilles run.

**Comment by MaximMoinat** [comment] 2024-02-13 14:16
Duplicate of: https://github.com/OHDSI/Achilles/issues/728, copying solution here:
> Sorry for cross-posting. I updated the forum thread on this topic asking if adding the following alleviates the issue:
> 
> ```r
> options(connectionObserver = NULL)
> ```
> 
> https://forums.ohdsi.org/t/getting-an-error-running-achilles/19224/18

**Closed** 2024-02-14 18:00 UTC
