### ISSUE TITLE
Impala misses table names

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#413] opened 2019-05-28 16:55 UTC
### Expected behavior
SQL statements are running properly

### Actual behavior
All SQL scripts are failing

### Steps to reproduce behavior
DBMS:
impala

Error:
java.sql.SQLException: [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Syntax error in line 1:
CREATE TABLE  STORED AS PARQUET AS
              ^
Encountered: STORED
Expected: DEFAULT, IF, IDENTIFIER

CAUSED BY: Exception: Syntax error
), Query: CREATE TABLE  STORED AS PARQUET AS
SELECT
2201 as analysis_id,
    CAST(m.note_type_CONCEPT_ID AS VARCHAR(255)) as stratum_1,
        cast(null as varchar(255)) as stratum_2, cast(null as varchar(255)) as stratum_3, cast(null as varchar(255)) as stratum_4, cast(null as varchar(255)) as stratum_5,
        COUNT(m.PERSON_ID) as count_value

FROM
omop_20183.note m
group by m.note_type_CONCEPT_ID.

SQL:
--HINT DISTRIBUTE_ON_KEY(stratum_1)
CREATE TABLE #.xy1srmzls_tmpach_2201
 STORED AS PARQUET AS
SELECT
2201 as analysis_id,
    CAST(m.note_type_CONCEPT_ID AS VARCHAR(255)) as stratum_1,
        cast(null as varchar(255)) as stratum_2, cast(null as varchar(255)) as stratum_3, cast(null as varchar(255)) as stratum_4, cast(null as varchar(255)) as stratum_5,
        COUNT(m.PERSON_ID) as count_value

FROM
omop_20183.note m
group by m.note_type_CONCEPT_ID

R version:
R version 3.5.2 (2018-12-20)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.6.6)
- DatabaseConnector (2.4.0)
- usethis (1.5.0)

**Comment by wivern** [comment] 2019-05-29 19:29
Could not reproduce on our environment:
![b9bd0bda-e5cc-4fc2-be92-8a8fb3a0f573](https://user-images.githubusercontent.com/1109753/58585377-37bbbd80-8261-11e9-84c2-585d213db580.png)

**Comment by alondhe** [comment] 2019-06-05 18:30
@konstjar -- we are focusing on resolving SQL compatibility in the 1,7.0 release. Can you help us in figuring out the correct syntax and then ultimately testing a branch against Impala to see if the solution works? I ask because none of us have Impala access or are Impala experts.

**Comment by acumarav** [comment] 2019-06-13 11:40
Hello @alondhe,
I have submit PR for this problem https://github.com/OHDSI/Achilles/pull/418. Please have a look. I did testing locally and can provide samples of fixed script.

Thank you!

**Closed** 2019-06-26 22:07 UTC
Labels: SQL compatibility
